# Generated by Django 6.0.6 on 2026-06-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('SESSION_UNLOCK', 'Unlock Sales Session'), ('SUBSCRIPTION', 'Subscription Payment'), ('SALE', 'POS Sale Payment'), ('OTHER', 'Other')], default='SESSION_UNLOCK', max_length=20),
        ),
    ]
