# Generated by Django 6.0.6 on 2026-06-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_payment_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='daily_free_sales',
            field=models.PositiveIntegerField(blank=True, default=20, help_text='Sales allowed before lock. Leave blank for unlimited (no lock ever applied).', null=True),
        ),
        migrations.AlterField(
            model_name='salessession',
            name='sales_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Snapshot of package limit at session start. Null means unlimited.', null=True),
        ),
    ]
