# Generated by Django 6.0.6 on 2026-06-28 21:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payment_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Hard expiry. After this, the subscription is expired even if sales_remaining > 0.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_purchase', to='core.payment'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sales_allocated',
            field=models.PositiveIntegerField(default=0, help_text='Total sales granted by this subscription purchase.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sales_remaining',
            field=models.PositiveIntegerField(default=0, help_text='Sales still available from this bundle.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('QUEUED', 'Queued'), ('EXPIRED', 'Expired / Consumed')], default='QUEUED', max_length=10),
        ),
        migrations.AlterField(
            model_name='salessession',
            name='sales_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Kept for display/history. Quota gate is now the Subscription stack.', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When this subscription became ACTIVE.', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='supermarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.supermarket'),
        ),
    ]
